from .keys import Keys
import pygame

PYGAME_TO_KEYS = {
    pygame.K_a: Keys.A,
    pygame.K_b: Keys.B,
    pygame.K_c: Keys.C,
    pygame.K_d: Keys.D,
    pygame.K_e: Keys.E,
    pygame.K_f: Keys.F,
    pygame.K_g: Keys.G,
    pygame.K_h: Keys.H,
    pygame.K_i: Keys.I,
    pygame.K_j: Keys.J,
    pygame.K_k: Keys.K,
    pygame.K_l: Keys.L,
    pygame.K_m: Keys.M,
    pygame.K_n: Keys.N,
    pygame.K_o: Keys.O,
    pygame.K_p: Keys.P,
    pygame.K_q: Keys.Q,
    pygame.K_r: Keys.R,
    pygame.K_s: Keys.S,
    pygame.K_t: Keys.T,
    pygame.K_u: Keys.U,
    pygame.K_v: Keys.V,
    pygame.K_w: Keys.W,
    pygame.K_x: Keys.X,
    pygame.K_y: Keys.Y,
    pygame.K_z: Keys.Z,

    pygame.K_0: Keys.N0,
    pygame.K_1: Keys.N1,
    pygame.K_2: Keys.N2,
    pygame.K_3: Keys.N3,
    pygame.K_4: Keys.N4,
    pygame.K_5: Keys.N5,
    pygame.K_6: Keys.N6,
    pygame.K_7: Keys.N7,
    pygame.K_8: Keys.N8,
    pygame.K_9: Keys.N9,

    pygame.K_SPACE: Keys.SPACE,
    pygame.K_RETURN: Keys.RETURN,
    pygame.K_ESCAPE: Keys.ESCAPE,
    pygame.K_BACKSPACE: Keys.BACKSPACE,
    pygame.K_TAB: Keys.TAB,
    pygame.K_DELETE: Keys.DELETE,

    pygame.K_UP: Keys.UP,
    pygame.K_DOWN: Keys.DOWN,
    pygame.K_LEFT: Keys.LEFT,
    pygame.K_RIGHT: Keys.RIGHT,

    pygame.K_F1: Keys.F1,
    pygame.K_F2: Keys.F2,
    pygame.K_F3: Keys.F3,
    pygame.K_F4: Keys.F4,
    pygame.K_F5: Keys.F5,
    pygame.K_F6: Keys.F6,
    pygame.K_F7: Keys.F7,
    pygame.K_F8: Keys.F8,
    pygame.K_F9: Keys.F9,
    pygame.K_F10: Keys.F10,
    pygame.K_F11: Keys.F11,
    pygame.K_F12: Keys.F12,
    pygame.K_F13: Keys.F13,
    pygame.K_F14: Keys.F14,
    pygame.K_F15: Keys.F15,

    pygame.K_LSHIFT: Keys.LSHIFT,
    pygame.K_RSHIFT: Keys.RSHIFT,
    pygame.K_LCTRL: Keys.LCTRL,
    pygame.K_RCTRL: Keys.RCTRL,
    pygame.K_LALT: Keys.LALT,
    pygame.K_RALT: Keys.RALT,
    pygame.K_LMETA: Keys.LMETA,
    pygame.K_RMETA: Keys.RMETA,

    pygame.K_CAPSLOCK: Keys.CAPSLOCK,
    pygame.K_NUMLOCK: Keys.NUMLOCK,
    pygame.K_SCROLLLOCK: Keys.SCROLLOCK,

    pygame.K_KP0: Keys.KP0,
    pygame.K_KP1: Keys.KP1,
    pygame.K_KP2: Keys.KP2,
    pygame.K_KP3: Keys.KP3,
    pygame.K_KP4: Keys.KP4,
    pygame.K_KP5: Keys.KP5,
    pygame.K_KP6: Keys.KP6,
    pygame.K_KP7: Keys.KP7,
    pygame.K_KP8: Keys.KP8,
    pygame.K_KP9: Keys.KP9,
    pygame.K_KP_ENTER: Keys.KP_ENTER,
    pygame.K_KP_PLUS: Keys.KP_PLUS,
    pygame.K_KP_MINUS: Keys.KP_MINUS,
    pygame.K_KP_MULTIPLY: Keys.KP_MULTIPLY,
    pygame.K_KP_DIVIDE: Keys.KP_DIVIDE,
}

KEYS_TO_PYGAME = {v: k for k, v in PYGAME_TO_KEYS.items()}